import { CountryCode } from "@/app/types";

export const POPULAR_COUNTRIES: CountryCode[] = [
  { code: "AW", name: "Aruba", dialCode: "", flag: "🇦🇼" },
  { code: "AF", name: "Afghanistan", dialCode: "93", flag: "🇦🇫" },
  { code: "AO", name: "Angola", dialCode: "", flag: "🇦🇴" },
  { code: "AI", name: "Anguilla", dialCode: "", flag: "🇦🇮" },
  { code: "AX", name: "Åland Islands", dialCode: "", flag: "🇦🇽" },
  { code: "AL", name: "Albania", dialCode: "", flag: "🇦🇱" },
  { code: "AD", name: "Andorra", dialCode: "", flag: "🇦🇩" },
  { code: "AE", name: "United Arab Emirates", dialCode: "971", flag: "🇦🇪" },
  { code: "AR", name: "Argentina", dialCode: "54", flag: "🇦🇷" },
  { code: "AM", name: "Armenia", dialCode: "", flag: "🇦🇲" },
  { code: "AS", name: "American Samoa", dialCode: "", flag: "🇦🇸" },
  { code: "AQ", name: "Antarctica", dialCode: "", flag: "🇦🇶" },
  { code: "TF", name: "French Southern Territories", dialCode: "", flag: "🇹🇫" },
  { code: "AG", name: "Antigua and Barbuda", dialCode: "", flag: "🇦🇬" },
  { code: "AU", name: "Australia", dialCode: "61", flag: "🇦🇺" },
  { code: "AT", name: "Austria", dialCode: "43", flag: "🇦🇹" },
  { code: "AZ", name: "Azerbaijan", dialCode: "", flag: "🇦🇿" },
  { code: "BI", name: "Burundi", dialCode: "", flag: "🇧🇮" },
  { code: "BE", name: "Belgium", dialCode: "32", flag: "🇧🇪" },
  { code: "BJ", name: "Benin", dialCode: "", flag: "🇧🇯" },
  { code: "BQ", name: "Bonaire, Sint Eustatius and Saba", dialCode: "", flag: "🇧🇶" },
  { code: "BF", name: "Burkina Faso", dialCode: "", flag: "🇧🇫" },
  { code: "BD", name: "Bangladesh", dialCode: "880", flag: "🇧🇩" },
  { code: "BG", name: "Bulgaria", dialCode: "359", flag: "🇧🇬" },
  { code: "BH", name: "Bahrain", dialCode: "", flag: "🇧🇭" },
  { code: "BS", name: "Bahamas", dialCode: "", flag: "🇧🇸" },
  { code: "BA", name: "Bosnia and Herzegovina", dialCode: "", flag: "🇧🇦" },
  { code: "BL", name: "Saint Barthélemy", dialCode: "", flag: "🇧🇱" },
  { code: "BY", name: "Belarus", dialCode: "", flag: "🇧🇾" },
  { code: "BZ", name: "Belize", dialCode: "", flag: "🇧🇿" },
  { code: "BM", name: "Bermuda", dialCode: "", flag: "🇧🇲" },
  { code: "BO", name: "Bolivia, Plurinational State of", dialCode: "", flag: "🇧🇴" },
  { code: "BR", name: "Brazil", dialCode: "55", flag: "🇧🇷" },
  { code: "BB", name: "Barbados", dialCode: "", flag: "🇧🇧" },
  { code: "BN", name: "Brunei Darussalam", dialCode: "", flag: "🇧🇳" },
  { code: "BT", name: "Bhutan", dialCode: "", flag: "🇧🇹" },
  { code: "BV", name: "Bouvet Island", dialCode: "", flag: "🇧🇻" },
  { code: "BW", name: "Botswana", dialCode: "", flag: "🇧🇼" },
  { code: "CF", name: "Central African Republic", dialCode: "", flag: "🇨🇫" },
  { code: "CA", name: "Canada", dialCode: "1", flag: "🇨🇦" },
  { code: "CC", name: "Cocos (Keeling) Islands", dialCode: "", flag: "🇨🇨" },
  { code: "CH", name: "Switzerland", dialCode: "41", flag: "🇨🇭" },
  { code: "CL", name: "Chile", dialCode: "56", flag: "🇨🇱" },
  { code: "CN", name: "China", dialCode: "86", flag: "🇨🇳" },
  { code: "CI", name: "Côte d'Ivoire", dialCode: "", flag: "🇨🇮" },
  { code: "CM", name: "Cameroon", dialCode: "237", flag: "🇨🇲" },
  { code: "CD", name: "Congo, The Democratic Republic of the", dialCode: "", flag: "🇨🇩" },
  { code: "CG", name: "Congo", dialCode: "", flag: "🇨🇬" },
  { code: "CK", name: "Cook Islands", dialCode: "", flag: "🇨🇰" },
  { code: "CO", name: "Colombia", dialCode: "57", flag: "🇨🇴" },
  { code: "KM", name: "Comoros", dialCode: "", flag: "🇰🇲" },
  { code: "CV", name: "Cabo Verde", dialCode: "", flag: "🇨🇻" },
  { code: "CR", name: "Costa Rica", dialCode: "", flag: "🇨🇷" },
  { code: "CU", name: "Cuba", dialCode: "53", flag: "🇨🇺" },
  { code: "CW", name: "Curaçao", dialCode: "", flag: "🇨🇼" },
  { code: "CX", name: "Christmas Island", dialCode: "", flag: "🇨🇽" },
  { code: "KY", name: "Cayman Islands", dialCode: "", flag: "🇰🇾" },
  { code: "CY", name: "Cyprus", dialCode: "", flag: "🇨🇾" },
  { code: "CZ", name: "Czechia", dialCode: "420", flag: "🇨🇿" },
  { code: "DE", name: "Germany", dialCode: "49", flag: "🇩🇪" },
  { code: "DJ", name: "Djibouti", dialCode: "", flag: "🇩🇯" },
  { code: "DM", name: "Dominica", dialCode: "", flag: "🇩🇲" },
  { code: "DK", name: "Denmark", dialCode: "45", flag: "🇩🇰" },
  { code: "DO", name: "Dominican Republic", dialCode: "", flag: "🇩🇴" },
  { code: "DZ", name: "Algeria", dialCode: "213", flag: "🇩🇿" },
  { code: "EC", name: "Ecuador", dialCode: "", flag: "🇪🇨" },
  { code: "EG", name: "Egypt", dialCode: "20", flag: "🇪🇬" },
  { code: "ER", name: "Eritrea", dialCode: "", flag: "🇪🇷" },
  { code: "EH", name: "Western Sahara", dialCode: "", flag: "🇪🇭" },
  { code: "ES", name: "Spain", dialCode: "34", flag: "🇪🇸" },
  { code: "EE", name: "Estonia", dialCode: "", flag: "🇪🇪" },
  { code: "ET", name: "Ethiopia", dialCode: "251", flag: "🇪🇹" },
  { code: "FI", name: "Finland", dialCode: "358", flag: "🇫🇮" },
  { code: "FJ", name: "Fiji", dialCode: "", flag: "🇫🇯" },
  { code: "FK", name: "Falkland Islands (Malvinas)", dialCode: "", flag: "🇫🇰" },
  { code: "FR", name: "France", dialCode: "33", flag: "🇫🇷" },
  { code: "FO", name: "Faroe Islands", dialCode: "", flag: "🇫🇴" },
  { code: "FM", name: "Micronesia, Federated States of", dialCode: "", flag: "🇫🇲" },
  { code: "GA", name: "Gabon", dialCode: "", flag: "🇬🇦" },
  { code: "GB", name: "United Kingdom", dialCode: "44", flag: "🇬🇧" },
  { code: "GE", name: "Georgia", dialCode: "", flag: "🇬🇪" },
  { code: "GG", name: "Guernsey", dialCode: "", flag: "🇬🇬" },
  { code: "GH", name: "Ghana", dialCode: "233", flag: "🇬🇭" },
  { code: "GI", name: "Gibraltar", dialCode: "", flag: "🇬🇮" },
  { code: "GN", name: "Guinea", dialCode: "", flag: "🇬🇳" },
  { code: "GP", name: "Guadeloupe", dialCode: "", flag: "🇬🇵" },
  { code: "GM", name: "Gambia", dialCode: "", flag: "🇬🇲" },
  { code: "GW", name: "Guinea-Bissau", dialCode: "", flag: "🇬🇼" },
  { code: "GQ", name: "Equatorial Guinea", dialCode: "", flag: "🇬🇶" },
  { code: "GR", name: "Greece", dialCode: "30", flag: "🇬🇷" },
  { code: "GD", name: "Grenada", dialCode: "", flag: "🇬🇩" },
  { code: "GL", name: "Greenland", dialCode: "", flag: "🇬🇱" },
  { code: "GT", name: "Guatemala", dialCode: "", flag: "🇬🇹" },
  { code: "GF", name: "French Guiana", dialCode: "", flag: "🇬🇫" },
  { code: "GU", name: "Guam", dialCode: "", flag: "🇬🇺" },
  { code: "GY", name: "Guyana", dialCode: "", flag: "🇬🇾" },
  { code: "HK", name: "Hong Kong", dialCode: "852", flag: "🇭🇰" },
  { code: "HM", name: "Heard Island and McDonald Islands", dialCode: "", flag: "🇭🇲" },
  { code: "HN", name: "Honduras", dialCode: "", flag: "🇭🇳" },
  { code: "HR", name: "Croatia", dialCode: "385", flag: "🇭🇷" },
  { code: "HT", name: "Haiti", dialCode: "", flag: "🇭🇹" },
  { code: "HU", name: "Hungary", dialCode: "36", flag: "🇭🇺" },
  { code: "ID", name: "Indonesia", dialCode: "62", flag: "🇮🇩" },
  { code: "IM", name: "Isle of Man", dialCode: "", flag: "🇮🇲" },
  { code: "IN", name: "India", dialCode: "91", flag: "🇮🇳" },
  { code: "IO", name: "British Indian Ocean Territory", dialCode: "", flag: "🇮🇴" },
  { code: "IE", name: "Ireland", dialCode: "353", flag: "🇮🇪" },
  { code: "IR", name: "Iran, Islamic Republic of", dialCode: "98", flag: "🇮🇷" },
  { code: "IQ", name: "Iraq", dialCode: "964", flag: "🇮🇶" },
  { code: "IS", name: "Iceland", dialCode: "", flag: "🇮🇸" },
  { code: "IT", name: "Italy", dialCode: "39", flag: "🇮🇹" },
  { code: "JM", name: "Jamaica", dialCode: "", flag: "🇯🇲" },
  { code: "JE", name: "Jersey", dialCode: "", flag: "🇯🇪" },
  { code: "JO", name: "Jordan", dialCode: "962", flag: "🇯🇴" },
  { code: "JP", name: "Japan", dialCode: "81", flag: "🇯🇵" },
  { code: "KZ", name: "Kazakhstan", dialCode: "7", flag: "🇰🇿" },
  { code: "KE", name: "Kenya", dialCode: "254", flag: "🇰🇪" },
  { code: "KG", name: "Kyrgyzstan", dialCode: "", flag: "🇰🇬" },
  { code: "KH", name: "Cambodia", dialCode: "855", flag: "🇰🇭" },
  { code: "KI", name: "Kiribati", dialCode: "", flag: "🇰🇮" },
  { code: "KN", name: "Saint Kitts and Nevis", dialCode: "", flag: "🇰🇳" },
  { code: "KR", name: "Korea, Republic of", dialCode: "82", flag: "🇰🇷" },
  { code: "KW", name: "Kuwait", dialCode: "965", flag: "🇰🇼" },
  { code: "LA", name: "Lao People's Democratic Republic", dialCode: "", flag: "🇱🇦" },
  { code: "LB", name: "Lebanon", dialCode: "961", flag: "🇱🇧" },
  { code: "LR", name: "Liberia", dialCode: "", flag: "🇱🇷" },
  { code: "LY", name: "Libya", dialCode: "", flag: "🇱🇾" },
  { code: "LC", name: "Saint Lucia", dialCode: "", flag: "🇱🇨" },
  { code: "LI", name: "Liechtenstein", dialCode: "", flag: "🇱🇮" },
  { code: "LK", name: "Sri Lanka", dialCode: "94", flag: "🇱🇰" },
  { code: "LS", name: "Lesotho", dialCode: "", flag: "🇱🇸" },
  { code: "LT", name: "Lithuania", dialCode: "", flag: "🇱🇹" },
  { code: "LU", name: "Luxembourg", dialCode: "", flag: "🇱🇺" },
  { code: "LV", name: "Latvia", dialCode: "", flag: "🇱🇻" },
  { code: "MO", name: "Macao", dialCode: "", flag: "🇲🇴" },
  { code: "MF", name: "Saint Martin (French part)", dialCode: "", flag: "🇲🇫" },
  { code: "MA", name: "Morocco", dialCode: "212", flag: "🇲🇦" },
  { code: "MC", name: "Monaco", dialCode: "", flag: "🇲🇨" },
  { code: "MD", name: "Moldova, Republic of", dialCode: "", flag: "🇲🇩" },
  { code: "MG", name: "Madagascar", dialCode: "", flag: "🇲🇬" },
  { code: "MV", name: "Maldives", dialCode: "", flag: "🇲🇻" },
  { code: "MX", name: "Mexico", dialCode: "52", flag: "🇲🇽" },
  { code: "MH", name: "Marshall Islands", dialCode: "", flag: "🇲🇭" },
  { code: "MK", name: "North Macedonia", dialCode: "", flag: "🇲🇰" },
  { code: "ML", name: "Mali", dialCode: "", flag: "🇲🇱" },
  { code: "MT", name: "Malta", dialCode: "", flag: "🇲🇹" },
  { code: "MM", name: "Myanmar", dialCode: "95", flag: "🇲🇲" },
  { code: "ME", name: "Montenegro", dialCode: "", flag: "🇲🇪" },
  { code: "MN", name: "Mongolia", dialCode: "976", flag: "🇲🇳" },
  { code: "MP", name: "Northern Mariana Islands", dialCode: "", flag: "🇲🇵" },
  { code: "MZ", name: "Mozambique", dialCode: "", flag: "🇲🇿" },
  { code: "MR", name: "Mauritania", dialCode: "", flag: "🇲🇷" },
  { code: "MS", name: "Montserrat", dialCode: "", flag: "🇲🇸" },
  { code: "MQ", name: "Martinique", dialCode: "", flag: "🇲🇶" },
  { code: "MU", name: "Mauritius", dialCode: "", flag: "🇲🇺" },
  { code: "MW", name: "Malawi", dialCode: "", flag: "🇲🇼" },
  { code: "MY", name: "Malaysia", dialCode: "60", flag: "🇲🇾" },
  { code: "YT", name: "Mayotte", dialCode: "", flag: "🇾🇹" },
  { code: "NA", name: "Namibia", dialCode: "", flag: "🇳🇦" },
  { code: "NC", name: "New Caledonia", dialCode: "", flag: "🇳🇨" },
  { code: "NE", name: "Niger", dialCode: "", flag: "🇳🇪" },
  { code: "NF", name: "Norfolk Island", dialCode: "", flag: "🇳🇫" },
  { code: "NG", name: "Nigeria", dialCode: "234", flag: "🇳🇬" },
  { code: "NI", name: "Nicaragua", dialCode: "", flag: "🇳🇮" },
  { code: "NU", name: "Niue", dialCode: "", flag: "🇳🇺" },
  { code: "NL", name: "Netherlands", dialCode: "31", flag: "🇳🇱" },
  { code: "NO", name: "Norway", dialCode: "47", flag: "🇳🇴" },
  { code: "NP", name: "Nepal", dialCode: "977", flag: "🇳🇵" },
  { code: "NR", name: "Nauru", dialCode: "", flag: "🇳🇷" },
  { code: "NZ", name: "New Zealand", dialCode: "64", flag: "🇳🇿" },
  { code: "OM", name: "Oman", dialCode: "968", flag: "🇴🇲" },
  { code: "PK", name: "Pakistan", dialCode: "92", flag: "🇵🇰" },
  { code: "PA", name: "Panama", dialCode: "", flag: "🇵🇦" },
  { code: "PN", name: "Pitcairn", dialCode: "", flag: "🇵🇳" },
  { code: "PE", name: "Peru", dialCode: "51", flag: "🇵🇪" },
  { code: "PH", name: "Philippines", dialCode: "63", flag: "🇵🇭" },
  { code: "PW", name: "Palau", dialCode: "", flag: "🇵🇼" },
  { code: "PG", name: "Papua New Guinea", dialCode: "", flag: "🇵🇬" },
  { code: "PL", name: "Poland", dialCode: "48", flag: "🇵🇱" },
  { code: "PR", name: "Puerto Rico", dialCode: "", flag: "🇵🇷" },
  { code: "KP", name: "Korea, Democratic People's Republic of", dialCode: "", flag: "🇰🇵" },
  { code: "PT", name: "Portugal", dialCode: "351", flag: "🇵🇹" },
  { code: "PY", name: "Paraguay", dialCode: "", flag: "🇵🇾" },
  { code: "PS", name: "Palestine, State of", dialCode: "", flag: "🇵🇸" },
  { code: "PF", name: "French Polynesia", dialCode: "", flag: "🇵🇫" },
  { code: "QA", name: "Qatar", dialCode: "", flag: "🇶🇦" },
  { code: "RE", name: "Réunion", dialCode: "", flag: "🇷🇪" },
  { code: "RO", name: "Romania", dialCode: "40", flag: "🇷🇴" },
  { code: "RU", name: "Russian Federation", dialCode: "7", flag: "🇷🇺" },
  { code: "RW", name: "Rwanda", dialCode: "", flag: "🇷🇼" },
  { code: "SA", name: "Saudi Arabia", dialCode: "966", flag: "🇸🇦" },
  { code: "SD", name: "Sudan", dialCode: "249", flag: "🇸🇩" },
  { code: "SN", name: "Senegal", dialCode: "221", flag: "🇸🇳" },
  { code: "SG", name: "Singapore", dialCode: "65", flag: "🇸🇬" },
  { code: "GS", name: "South Georgia and the South Sandwich Islands", dialCode: "", flag: "🇬🇸" },
  { code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", dialCode: "", flag: "🇸🇭" },
  { code: "SJ", name: "Svalbard and Jan Mayen", dialCode: "", flag: "🇸🇯" },
  { code: "SB", name: "Solomon Islands", dialCode: "", flag: "🇸🇧" },
  { code: "SL", name: "Sierra Leone", dialCode: "", flag: "🇸🇱" },
  { code: "SV", name: "El Salvador", dialCode: "", flag: "🇸🇻" },
  { code: "SM", name: "San Marino", dialCode: "", flag: "🇸🇲" },
  { code: "SO", name: "Somalia", dialCode: "", flag: "🇸🇴" },
  { code: "PM", name: "Saint Pierre and Miquelon", dialCode: "", flag: "🇵🇲" },
  { code: "RS", name: "Serbia", dialCode: "381", flag: "🇷🇸" },
  { code: "SS", name: "South Sudan", dialCode: "", flag: "🇸🇸" },
  { code: "ST", name: "Sao Tome and Principe", dialCode: "", flag: "🇸🇹" },
  { code: "SR", name: "Suriname", dialCode: "", flag: "🇸🇷" },
  { code: "SK", name: "Slovakia", dialCode: "421", flag: "🇸🇰" },
  { code: "SI", name: "Slovenia", dialCode: "", flag: "🇸🇮" },
  { code: "SE", name: "Sweden", dialCode: "46", flag: "🇸🇪" },
  { code: "SZ", name: "Eswatini", dialCode: "", flag: "🇸🇿" },
  { code: "SX", name: "Sint Maarten (Dutch part)", dialCode: "", flag: "🇸🇽" },
  { code: "SC", name: "Seychelles", dialCode: "", flag: "🇸🇨" },
  { code: "SY", name: "Syrian Arab Republic", dialCode: "963", flag: "🇸🇾" },
  { code: "TC", name: "Turks and Caicos Islands", dialCode: "", flag: "🇹🇨" },
  { code: "TD", name: "Chad", dialCode: "", flag: "🇹🇩" },
  { code: "TG", name: "Togo", dialCode: "", flag: "🇹🇬" },
  { code: "TH", name: "Thailand", dialCode: "66", flag: "🇹🇭" },
  { code: "TJ", name: "Tajikistan", dialCode: "", flag: "🇹🇯" },
  { code: "TK", name: "Tokelau", dialCode: "", flag: "🇹🇰" },
  { code: "TM", name: "Turkmenistan", dialCode: "", flag: "🇹🇲" },
  { code: "TL", name: "Timor-Leste", dialCode: "", flag: "🇹🇱" },
  { code: "TO", name: "Tonga", dialCode: "", flag: "🇹🇴" },
  { code: "TT", name: "Trinidad and Tobago", dialCode: "", flag: "🇹🇹" },
  { code: "TN", name: "Tunisia", dialCode: "", flag: "🇹🇳" },
  { code: "TR", name: "Turkey", dialCode: "90", flag: "🇹🇷" },
  { code: "TV", name: "Tuvalu", dialCode: "", flag: "🇹🇻" },
  { code: "TW", name: "Taiwan, Province of China", dialCode: "886", flag: "🇹🇼" },
  { code: "TZ", name: "Tanzania, United Republic of", dialCode: "255", flag: "🇹🇿" },
  { code: "UG", name: "Uganda", dialCode: "256", flag: "🇺🇬" },
  { code: "UA", name: "Ukraine", dialCode: "380", flag: "🇺🇦" },
  { code: "UM", name: "United States Minor Outlying Islands", dialCode: "", flag: "🇺🇲" },
  { code: "UY", name: "Uruguay", dialCode: "", flag: "🇺🇾" },
  { code: "US", name: "United States", dialCode: "1", flag: "🇺🇸" },
  { code: "UZ", name: "Uzbekistan", dialCode: "998", flag: "🇺🇿" },
  { code: "VA", name: "Holy See (Vatican City State)", dialCode: "", flag: "🇻🇦" },
  { code: "VC", name: "Saint Vincent and the Grenadines", dialCode: "", flag: "🇻🇨" },
  { code: "VE", name: "Venezuela, Bolivarian Republic of", dialCode: "58", flag: "🇻🇪" },
  { code: "VG", name: "Virgin Islands, British", dialCode: "", flag: "🇻🇬" },
  { code: "VI", name: "Virgin Islands, U.S.", dialCode: "", flag: "🇻🇮" },
  { code: "VN", name: "Viet Nam", dialCode: "84", flag: "🇻🇳" },
  { code: "VU", name: "Vanuatu", dialCode: "", flag: "🇻🇺" },
  { code: "WF", name: "Wallis and Futuna", dialCode: "", flag: "🇼🇫" },
  { code: "WS", name: "Samoa", dialCode: "", flag: "🇼🇸" },
  { code: "YE", name: "Yemen", dialCode: "967", flag: "🇾🇪" },
  { code: "ZA", name: "South Africa", dialCode: "27", flag: "🇿🇦" },
  { code: "ZM", name: "Zambia", dialCode: "260", flag: "🇿🇲" },
  { code: "ZW", name: "Zimbabwe", dialCode: "263", flag: "🇿🇼" },
];